version: "3.6"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ee:latest
    ports:
      - 9443:9443
    volumes:
      - $HOME/docker_data/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped